name: pravda_news
description: "Soviet news app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  logging: ^1.2.0
  provider: ^6.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  fonts:
    - family: Soviet-large
      fonts:
        - asset: fonts/soviet_font.ttf
    - family: Times
      fonts:
        - asset: fonts/times.ttf
  assets:
    - assets/star.png
    - assets/img.png
    - assets/hammer.png
  uses-material-design: true
