name: Example-ci
on: [push, workflow_dispatch]
jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter analyze .
      - run: dart format --set-exit-if-changed  .

  build-android:
    needs: [flutter-analyze]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: app-release.apk file
          path: build/app/outputs/flutter-apk/app-release.apk

